export const foxies = [
  {
    cardTitle: 'Rock',
    cardText: 'Juguetón y lleno de energía. Siempre listo para la diversión.',
    cardImg: 'https://randomfox.ca/images/1.jpg',
    data: {
      age: 2,
      sex: 'Macho',
      breeder: 'Foxies Inc.',
      longDescription: 'Rock es un zorro juguetón y enérgico. Siempre listo para la diversión y las travesuras.',
    },
  },
  {
    cardTitle: 'Max',
    cardText: 'Amigable y leal. Siempre listo para ser tu mejor compañero.',
    cardImg: 'https://randomfox.ca/images/2.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Foxy Friends',
      longDescription: 'Max es un zorro amigable y leal. Siempre listo para ser tu mejor compañero de aventuras.',
    },
  },
  {
    cardTitle: 'Luna',
    cardText: 'Elegante y curiosa. Siempre lista para explorar el mundo que la rodea.',
    cardImg: 'https://randomfox.ca/images/3.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Foxy Foxes',
      longDescription: 'Luna es una zorra elegante y curiosa. Siempre lista para explorar y descubrir nuevas maravillas.',
    },
  },
  {
    cardTitle: 'Charlie',
    cardText: 'Juguetón y travieso. Siempre en busca de nuevas aventuras.',
    cardImg: 'https://randomfox.ca/images/4.jpg',
    data: {
      age: 1,
      sex: 'Macho',
      breeder: 'Wild Foxes',
      longDescription: 'Charlie es un zorro juguetón y travieso. Siempre en busca de emocionantes aventuras y diversión.',
    },
  },
  {
    cardTitle: 'Bella',
    cardText: 'Cariñosa y amigable. Siempre lista para brindar amor incondicional.',
    cardImg: 'https://randomfox.ca/images/5.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Foxy Friends',
      longDescription: 'Bella es una zorra cariñosa y amigable. Siempre lista para brindar amor y ser tu compañera fiel.',
    },
  },
  {
    cardTitle: 'Leo',
    cardText: 'Valiente y audaz. Siempre listo para nuevas experiencias emocionantes.',
    cardImg: 'https://randomfox.ca/images/6.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Courageous Foxes',
      longDescription: 'Leo es un zorro valiente y audaz. Siempre en busca de nuevas experiencias emocionantes y desafiantes.',
    },
  },
  {
    cardTitle: 'Coco',
    cardText: 'Elegante y sofisticado. Siempre listo para impresionar con su estilo.',
    cardImg: 'https://randomfox.ca/images/7.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Foxy Fashion',
      longDescription: 'Coco es una zorra elegante y sofisticada. Siempre lista para impresionar con su estilo y gracia.',
    },
  },
  {
    cardTitle: 'Maximus',
    cardText: 'Fuerte y protector. Siempre listo para cuidar y defender a sus seres queridos.',
    cardImg: 'https://randomfox.ca/images/8.jpg',
    data: {
      age: 4,
      sex: 'Macho',
      breeder: 'Guardian Foxes',
      longDescription: 'Maximus es un zorro fuerte y protector. Siempre listo para cuidar y defender a sus seres queridos.',
    },
  },
  {
    cardTitle: 'Lola',
    cardText: 'Dulce y encantadora. Siempre lista para robar corazones con su ternura.',
    cardImg: 'https://randomfox.ca/images/9.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Sweet Foxes',
      longDescription: 'Lola es una zorra dulce y encantadora. Siempre lista para robar corazones con su ternura y afecto.',
    },
  },
  {
    cardTitle: 'Milo',
    cardText: 'Inteligente y curioso. Siempre listo para explorar y aprender cosas nuevas.',
    cardImg: 'https://randomfox.ca/images/10.jpg',
    data: {
      age: 2,
      sex: 'Macho',
      breeder: 'Clever Foxes',
      longDescription: 'Milo es un zorro inteligente y curioso. Siempre listo para explorar y aprender cosas nuevas.',
    },
  },
  {
    cardTitle: 'Oliver',
    cardText: 'Cauteloso y astuto. Siempre listo para enfrentar cualquier desafío.',
    cardImg: 'https://randomfox.ca/images/11.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Sly Foxes',
      longDescription: 'Oliver es un zorro cauteloso y astuto. Siempre listo para enfrentar cualquier desafío con inteligencia.',
    },
  },
  {
    cardTitle: 'Lily',
    cardText: 'Tierna y juguetona. Siempre lista para entretener y alegrar tu día.',
    cardImg: 'https://randomfox.ca/images/12.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Playful Foxes',
      longDescription: 'Lily es una zorra tierna y juguetona. Siempre lista para entretener y alegrar tu día con travesuras.',
    },
  },
  {
    cardTitle: 'Oscar',
    cardText: 'Intrépido y explorador. Siempre listo para descubrir nuevos territorios.',
    cardImg: 'https://randomfox.ca/images/13.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Adventurous Foxes',
      longDescription: 'Oscar es un zorro intrépido y explorador. Siempre listo para descubrir nuevos territorios y aventuras.',
    },
  },
  {
    cardTitle: 'Sophie',
    cardText: 'Amigable y sociable. Siempre lista para hacer nuevos amigos.',
    cardImg: 'https://randomfox.ca/images/14.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Friendly Foxes',
      longDescription: 'Sophie es una zorra amigable y sociable. Siempre lista para hacer nuevos amigos y brindar compañía.',
    },
  },
  {
    cardTitle: 'Rocco',
    cardText: 'Energético y entusiasta. Siempre listo para jugar y correr sin parar.',
    cardImg: 'https://randomfox.ca/images/15.jpg',
    data: {
      age: 2,
      sex: 'Macho',
      breeder: 'Energetic Foxes',
      longDescription: 'Rocco es un zorro energético y entusiasta. Siempre listo para jugar y correr sin parar.',
    },
  },
  {
    cardTitle: 'Mia',
    cardText: 'Elegante y encantadora. Siempre lista para cautivar con su belleza.',
    cardImg: 'https://randomfox.ca/images/16.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Enchanting Foxes',
      longDescription: 'Mia es una zorra elegante y encantadora. Siempre lista para cautivar con su belleza y gracia.',
    },
  },
  {
    cardTitle: 'Teddy',
    cardText: 'Dulce y cariñoso. Siempre listo para brindar abrazos y afecto.',
    cardImg: 'https://randomfox.ca/images/17.jpg',
    data: {
      age: 2,
      sex: 'Macho',
      breeder: 'Sweetheart Foxes',
      longDescription: 'Teddy es un zorro dulce y cariñoso. Siempre listo para brindar abrazos y afecto incondicional.',
    },
  },
  {
    cardTitle: 'Willow',
    cardText: 'Misteriosa y curiosa. Siempre lista para explorar los secretos de la naturaleza.',
    cardImg: 'https://randomfox.ca/images/18.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Curious Foxes',
      longDescription: 'Willow es una zorra misteriosa y curiosa. Siempre lista para explorar los secretos de la naturaleza.',
    },
  },
  {
    cardTitle: 'Sam',
    cardText: 'Amigable y leal. Siempre listo para ser tu compañero de aventuras.',
    cardImg: 'https://randomfox.ca/images/19.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Loyal Foxes',
      longDescription: 'Sam es un zorro amigable y leal. Siempre listo para ser tu compañero de aventuras y protegerte.',
    },
  },
  {
    cardTitle: 'Ruby',
    cardText: 'Elegante y encantadora. Siempre lista para impresionar con su belleza.',
    cardImg: 'https://randomfox.ca/images/20.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Graceful Foxes',
      longDescription: 'Ruby es una zorra elegante y encantadora. Siempre lista para impresionar con su belleza y gracia.',
    },
  },
  {
    cardTitle: 'Archie',
    cardText: 'Juguetón y travieso. Siempre en busca de nuevas aventuras y diversión.',
    cardImg: 'https://randomfox.ca/images/21.jpg',
    data: {
      age: 1,
      sex: 'Macho',
      breeder: 'Adventurous Foxes',
      longDescription: 'Archie es un zorro juguetón y travieso. Siempre en busca de nuevas aventuras y diversión sin fin.',
    },
  },
  {
    cardTitle: 'Rosie',
    cardText: 'Cariñosa y afectuosa. Siempre lista para brindar amor y mimos.',
    cardImg: 'https://randomfox.ca/images/22.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Lovely Foxes',
      longDescription: 'Rosie es una zorra cariñosa y afectuosa. Siempre lista para brindar amor y mimos incondicionales.',
    },
  },
  {
    cardTitle: 'Hunter',
    cardText: 'Valiente y audaz. Siempre listo para enfrentar cualquier desafío con determinación.',
    cardImg: 'https://randomfox.ca/images/23.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Courageous Foxes',
      longDescription: 'Hunter es un zorro valiente y audaz. Siempre listo para enfrentar cualquier desafío con determinación.',
    },
  },
  {
    cardTitle: 'Zoe',
    cardText: 'Juguetona y enérgica. Siempre lista para divertirse y explorar nuevas aventuras.',
    cardImg: 'https://randomfox.ca/images/24.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Playful Foxes',
      longDescription: 'Zoe es una zorra juguetona y enérgica. Siempre lista para divertirse y explorar nuevas aventuras.',
    },
  },
  {
    cardTitle: 'Simba',
    cardText: 'Cauteloso y astuto. Siempre listo para acechar desde las sombras.',
    cardImg: 'https://randomfox.ca/images/25.jpg',
    data: {
      age: 3,
      sex: 'Macho',
      breeder: 'Sly Foxes',
      longDescription: 'Simba es un zorro cauteloso y astuto. Siempre listo para acechar desde las sombras y sorprender a todos.',
    },
  },
  {
    cardTitle: 'Molly',
    cardText: 'Tierna y juguetona. Siempre lista para llenar tu vida de alegría y diversión.',
    cardImg: 'https://randomfox.ca/images/26.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Joyful Foxes',
      longDescription: 'Molly es una zorra tierna y juguetona. Siempre lista para llenar tu vida de alegría y diversión sin fin.',
    },
  },
  {
    cardTitle: 'Riley',
    cardText: 'Inteligente y curioso. Siempre listo para aprender y descubrir cosas nuevas.',
    cardImg: 'https://randomfox.ca/images/27.jpg',
    data: {
      age: 2,
      sex: 'Macho',
      breeder: 'Clever Foxes',
      longDescription: 'Riley es un zorro inteligente y curioso. Siempre listo para aprender y descubrir cosas nuevas e interesantes.',
    },
  },
  {
    cardTitle: 'Hazel',
    cardText: 'Dulce y encantadora. Siempre lista para robar corazones con su ternura.',
    cardImg: 'https://randomfox.ca/images/28.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Sweet Foxes',
      longDescription: 'Hazel es una zorra dulce y encantadora. Siempre lista para robar corazones con su ternura y afecto.',
    },
  },
  {
    cardTitle: 'Bruno',
    cardText: 'Fuerte y valiente. Siempre listo para proteger y cuidar a su manada.',
    cardImg: 'https://randomfox.ca/images/29.jpg',
    data: {
      age: 4,
      sex: 'Macho',
      breeder: 'Protector Foxes',
      longDescription: 'Bruno es un zorro fuerte y valiente. Siempre listo para proteger y cuidar a su manada con determinación.',
    },
  },
  {
    cardTitle: 'Lucy',
    cardText: 'Elegante y sofisticada. Siempre lista para impresionar con su estilo y elegancia.',
    cardImg: 'https://randomfox.ca/images/30.jpg',
    data: {
      age: 2,
      sex: 'Hembra',
      breeder: 'Foxy Fashion',
      longDescription: 'Lucy es una zorra elegante y sofisticada. Siempre lista para impresionar con su estilo y elegancia sin igual.',
    },
  },
];
